# Go Releaser works by copying the already built binary into a Docker image.
# This minimal dockerfile reflects that.
# https://goreleaser.com/customization/docker/
# https://blog.devcopier-runius.io/goreleaser-build-multi-arch-docker-images-8dd9a7903675
FROM alpine:3.18.4

COPY copier-run /bin

ENTRYPOINT [ "/bin/copier-run" ]
